apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: xzcz6k1xk-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/xzcz6k1xk-dotnet-basic-gitops